#pragma once

// ESP32-2432S028R / Cheap Yellow Display configuration.

#define DISPLAY_ROTATION 1
#define TFT_BACKLIGHT_PIN 21

#define TOUCH_CS 33
#define TOUCH_IRQ 36
#define TOUCH_SCLK 25
#define TOUCH_MISO 39
#define TOUCH_MOSI 32

#define SD_CS 5
#define SD_SCLK 18
#define SD_MISO 19
#define SD_MOSI 23

#define AUDIO_DAC_PIN 26

#define CYD_RGB_LED_ENABLE 1
#define CYD_RGB_RED_PIN 4
#define CYD_RGB_GREEN_PIN 16
#define CYD_RGB_BLUE_PIN 17
#define CYD_RGB_ACTIVE_LOW 1
#define CYD_RGB_MAX_BRIGHTNESS 64

// Wolf3D display profile.
#define CYD_WOLF_VIEW_SIZE 20

#define CYD_WOLF_BUILD_NUMBER 20

#define CYD_WOLF_PALETTE_BRIGHTNESS_PERCENT 160

#define CYD_WOLF_SKIP_BOOT_SCREENS 1

// Renderer feature flags.
#define CYD_WOLF_DRAW_SPRITES 1
#define CYD_WOLF_DRAW_WEAPON 1
#define CYD_WOLF_DRAW_STATUSBAR_ART 0

#define CYD_WOLF_FLAT_WALLS 1
#define CYD_WOLF_WALL_TEXTURE_CACHE 1
#define CYD_WOLF_WALL_TEXTURE_MIN_PIC 0

// Sprite quality/performance profile.
#define CYD_WOLF_FAST_SPRITES 1
#define CYD_WOLF_FAST_SPRITE_MIN_HEIGHT 32
#define CYD_WOLF_FAST_DECOR_SPRITE_MIN_HEIGHT 32
#define CYD_WOLF_FAST_WEAPON_SPRITES 1
#define CYD_WOLF_HIDE_TINY_DECOR_SPRITES 1
#define CYD_WOLF_TINY_DECOR_MAX_HEIGHT 14
#define CYD_WOLF_DRAW_STATIC_DECOR 1
#define CYD_WOLF_MAX_STATIC_DECOR_SPRITES 8
#define CYD_WOLF_STATIC_DECOR_IMPOSTORS 1
#define CYD_WOLF_STATIC_DECOR_CACHE 1
#define CYD_WOLF_DECOR_CACHE_COUNT 48
#define CYD_WOLF_DECOR_OCCLUSION_MARGIN 16
#define CYD_WOLF_SPRITE_BUDGET_US 0

// Diagnostics.
#define CYD_WOLF_ENABLE_PERF_LOGS 0
#define CYD_WOLF_ENABLE_FRAME_HEARTBEAT 0
#define CYD_WOLF_RESOURCE_TRACE 0
#define CYD_WOLF_RESOURCE_TRACE_INTERVAL_MS 3000

// VSWAP hot-page cache.
#define CYD_WOLF_HOT_PAGE_CACHE 1
#define CYD_WOLF_HOT_PAGE_CACHE_SLOTS 6
#define CYD_WOLF_HOT_PAGE_CACHE_MAX_BYTES 1536

#define CYD_WOLF_SCREEN_FLASHES 0

// CYD memory profile.
#define CYD_WOLF_MAXACTORS 128
#define CYD_WOLF_MAXSTATS 400
#define CYD_WOLF_MAXVISABLE 128

// Audio.
#define CYD_WOLF_BASIC_SOUND 1
#define CYD_WOLF_SOUND_DUTY 43

// XPT2046 touch calibration.
#define TOUCH_MIN_X 200
#define TOUCH_MAX_X 3900
#define TOUCH_MIN_Y 200
#define TOUCH_MAX_Y 3900
#define TOUCH_SWAP_XY 1
#define TOUCH_INVERT_X 0
#define TOUCH_INVERT_Y 0
