#pragma once

// ESP32-2432S028R / Cheap Yellow Display configuration.

#define DISPLAY_ROTATION 1
#define TFT_BACKLIGHT_PIN 21

#define TOUCH_CS 33
#define TOUCH_IRQ 36
#define TOUCH_SCLK 25
#define TOUCH_MISO 39
#define TOUCH_MOSI 32

#define SD_CS 5
#define SD_SCLK 18
#define SD_MISO 19
#define SD_MOSI 23

#define AUDIO_DAC_PIN 26

#define CYD_RGB_LED_ENABLE 1
#define CYD_RGB_RED_PIN 4
#define CYD_RGB_GREEN_PIN 16
#define CYD_RGB_BLUE_PIN 17
#define CYD_RGB_ACTIVE_LOW 1
#define CYD_RGB_MAX_BRIGHTNESS 64

// Wolf3D display profile.
#define CYD_WOLF_VIEW_SIZE 20

#ifndef CYD_WOLF_BUILD_NUMBER
#define CYD_WOLF_BUILD_NUMBER 72
#endif

#define CYD_WOLF_PALETTE_BRIGHTNESS_PERCENT 100

#define CYD_WOLF_SKIP_BOOT_SCREENS 0

// Renderer feature flags.
#define CYD_WOLF_DRAW_SPRITES 1
#define CYD_WOLF_DRAW_WEAPON 1
#define CYD_WOLF_DRAW_STATUSBAR_ART 0
#define CYD_WOLF_USE_DMA_PRESENT 1
#define CYD_WOLF_DMA_STRIPE_ROWS 2

#define CYD_WOLF_FLAT_WALLS 0
#define CYD_WOLF_LOW_RES_WALL_TEXTURES 1
#define CYD_WOLF_WALL_TEXTURE_CACHE 1
#ifndef CYD_WOLF_WALL_TEXTURE_CACHE_SLOTS
#define CYD_WOLF_WALL_TEXTURE_CACHE_SLOTS 32
#endif
#ifndef CYD_WOLF_WALL_TEXTURE_DIM
#define CYD_WOLF_WALL_TEXTURE_DIM 8
#endif
#define CYD_WOLF_WALL_COLUMN_STEP 2
#define CYD_WOLF_WALL_TEXTURE_MIN_PIC 0

// Sprite quality/performance profile.
#define CYD_WOLF_FAST_SPRITES 1
#define CYD_WOLF_FAST_SPRITE_MIN_HEIGHT 32
#define CYD_WOLF_FAST_DECOR_SPRITE_MIN_HEIGHT 32
#define CYD_WOLF_FAST_WEAPON_SPRITES 1
#define CYD_WOLF_DOWNSAMPLED_WEAPON 1
#define CYD_WOLF_WEAPON_CACHE_DIM 32
#define CYD_WOLF_WEAPON_CACHE_SLOTS 4
#define CYD_WOLF_ACTOR_IMPOSTORS 0
#define CYD_WOLF_HIDE_TINY_DECOR_SPRITES 1
#define CYD_WOLF_TINY_DECOR_MAX_HEIGHT 14
#define CYD_WOLF_DRAW_STATIC_DECOR 1
#define CYD_WOLF_MAX_STATIC_DECOR_SPRITES 8
#ifndef CYD_WOLF_STATIC_DECOR_IMPOSTORS
#define CYD_WOLF_STATIC_DECOR_IMPOSTORS 1
#endif
#ifndef CYD_WOLF_STATIC_DECOR_CACHE
#define CYD_WOLF_STATIC_DECOR_CACHE 1
#endif
#ifndef CYD_WOLF_DECOR_CACHE_COUNT
#define CYD_WOLF_DECOR_CACHE_COUNT 8
#endif
#define CYD_WOLF_DECOR_OCCLUSION_MARGIN 16
#define CYD_WOLF_SPRITE_BUDGET_US 0

// Diagnostics.
#define CYD_WOLF_DEMO_MODE 0
#define CYD_WOLF_DEMO_NUMBER 1
#define CYD_WOLF_DEMO_CYCLE 0
#define CYD_WOLF_ENABLE_PERF_LOGS 1
#define CYD_WOLF_ENABLE_FRAME_HEARTBEAT 0
#define CYD_WOLF_RESOURCE_TRACE 0
#define CYD_WOLF_RESOURCE_TRACE_INTERVAL_MS 1000

// VSWAP hot-page cache.
#define CYD_WOLF_HOT_PAGE_CACHE 1
#define CYD_WOLF_HOT_PAGE_CACHE_SLOTS 2
#define CYD_WOLF_HOT_PAGE_CACHE_MAX_BYTES 1536

#define CYD_WOLF_SCREEN_FLASHES 1

// S2 Face Serial connection (TX=1 on programming port P1, RX=3)
#define CYD_S2_FACE_ENABLE 1
#define CYD_S2_FACE_DOWNSAMPLE 1
#define CYD_S2_FACE_LATCH_SURFACES 0
#define CYD_S2_FACE_TX_PIN 1
#define CYD_S2_FACE_RX_PIN 3

// MCP23017 port expander configuration
#define CYD_MCP23017_ENABLE 1
#define CYD_MCP23017_SDA 27
#define CYD_MCP23017_SCL 22


// CYD memory profile.
#define CYD_WOLF_MAXACTORS 64
#define CYD_WOLF_MAXSTATS 192
#define CYD_WOLF_MAXVISABLE 64
#define CYD_WOLF_STATIC_DECOR_RESERVE_SLOTS 24

// Audio.
#define CYD_WOLF_BASIC_SOUND 1
#define CYD_WOLF_SOUND_TRACE 0
#define CYD_WOLF_SOUND_DUTY 43

// XPT2046 touch calibration.
#define TOUCH_MIN_X 200
#define TOUCH_MAX_X 3900
#define TOUCH_MIN_Y 200
#define TOUCH_MAX_Y 3900
#define TOUCH_SWAP_XY 1
#define TOUCH_INVERT_X 0
#define TOUCH_INVERT_Y 0

#ifdef LCDWIKI_ES3C28P
#undef DISPLAY_ROTATION
#undef TFT_BACKLIGHT_PIN
#undef TOUCH_CS
#undef TOUCH_IRQ
#undef TOUCH_SCLK
#undef TOUCH_MISO
#undef TOUCH_MOSI
#undef SD_CS
#undef SD_SCLK
#undef SD_MISO
#undef SD_MOSI
#undef AUDIO_DAC_PIN
#undef CYD_RGB_LED_ENABLE
#undef CYD_MCP23017_ENABLE
#undef CYD_S2_FACE_ENABLE
#undef CYD_WOLF_BASIC_SOUND
#undef CYD_WOLF_LOW_RES_WALL_TEXTURES
#undef CYD_WOLF_WALL_TEXTURE_DIM
#undef CYD_WOLF_DOWNSAMPLED_WEAPON
#undef CYD_WOLF_FAST_WEAPON_SPRITES
#undef CYD_WOLF_WALL_COLUMN_STEP
#undef CYD_WOLF_USE_DMA_PRESENT
#undef CYD_WOLF_DMA_STRIPE_ROWS
#undef CYD_WOLF_DEMO_MODE
#undef CYD_WOLF_DEMO_CYCLE

#define DISPLAY_ROTATION 1
#define TFT_BACKLIGHT_PIN 45
#define TOUCH_CS -1
#define TOUCH_IRQ 17
#define TOUCH_SCLK 15
#define TOUCH_MISO 16
#define TOUCH_MOSI 16
#define SD_CS 47
#define SD_SCLK 38
#define SD_MISO 39
#define SD_MOSI 40
#define AUDIO_DAC_PIN -1
#define CYD_RGB_LED_ENABLE 0
#define CYD_MCP23017_ENABLE 0
#define CYD_S2_FACE_ENABLE 0
#define CYD_WOLF_BASIC_SOUND 0
#define CYD_WOLF_LOW_RES_WALL_TEXTURES 0
#define CYD_WOLF_WALL_TEXTURE_DIM 64
#define CYD_WOLF_DOWNSAMPLED_WEAPON 0
#define CYD_WOLF_FAST_WEAPON_SPRITES 0
#define CYD_WOLF_WALL_COLUMN_STEP 1
#define CYD_WOLF_USE_DMA_PRESENT 0
#define CYD_WOLF_DMA_STRIPE_ROWS 8
#define CYD_WOLF_DEMO_MODE 1
#define CYD_WOLF_DEMO_CYCLE 1
#endif
